name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  stage-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Install LibreOffice
        run: sudo apt install libreoffice --no-install-recommends
      
      - name: Download from Google Drive
        run: python scripts/download_drive_contents.py