name: Update Website Builder

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # This next bit is necessary (otherwise we get issues when we merge)
        with:
          fetch-depth: 0
          ref: refs/heads/main

      - name: Merge updates
        run: |
          git remote add template https://github.com/Rachmanin0xFF/docs-to-pages.git || echo "Upstream already exists"
          git fetch origin
          git fetch template
          git checkout --ours LINK_TO_DRIVE_FOLDER
          git checkout --ours CONFIG.ini
          git checkout --ours templates
          git add LINK_TO_DRIVE_FOLDER
          git add CONFIG.ini
          git add templates
          git config --global user.name '${{ github.actor }} - Automated'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git rebase template/main
      
      - name: Commit resolved changes
        run: |
          git commit -m "Routine " || echo "No changes to commit"
      
      - name: Push changes
        run: |
          git push origin main
